## Normal

In [1]:
import torch
import sys 
sys.path.append('/home/louis/Documents/Master_project/social-nce/')
import os
from torch.utils.data.dataloader import DataLoader
import numpy as np
import pickle
from crowd_nav.utils.dataset import ImitDataset, ImitDatasetTraj
from crowd_nav.policy.sail_traj import ExtendedNetworkTraj
from crowd_nav.policy.policy_factory import policy_factory
import configparser
import gym
import sys
sys.path.append('..')
from crowd_sim.envs.utils.robot import Robot
from crowd_sim.envs.crowd_sim import CrowdSim
from crowd_nav.utils.explorer import ExplorerDs

In [2]:
data = torch.load('data/demonstrate/aggressive/data_imit.pt')

In [3]:
type(data[1]), data[1].shape, data[0].shape

(torch.Tensor, torch.Size([109271, 5, 4]), torch.Size([109271, 6]))

In [5]:
human_pos_per_ep = []
prev_val = data[3][0].item()
ep_pos = []
for i in range(len(data[0])) :
    hum_pos, val = data[1][i], data[3][i]
    if abs(val.item()-prev_val) > 1e-1 :
        human_pos_per_ep.append(ep_pos)
        ep_pos=[]
    ep_pos.append(hum_pos)
    prev_val = val
    if i==len(data[0])-1 :
        human_pos_per_ep.append(ep_pos)

In [6]:
obs_memory = 10
human_positions_mem = []
for episode in human_pos_per_ep :
    episode_start = True
    for human_positions in episode :
        if episode_start :
            episode_start = False 
            human_pos_stack = [human_positions] * obs_memory
        else :
            human_pos_stack.append(human_positions)
            human_pos_stack = human_pos_stack[1:]
        human_positions_mem.append(torch.stack(human_pos_stack))

In [7]:
human_positions_mem = torch.stack(human_positions_mem)

In [8]:
human_positions_mem.shape

torch.Size([109271, 10, 5, 4])

In [9]:
data_obs = [data[0], human_positions_mem, data[2], data[3]]

In [10]:
torch.save(data_obs, 'data/demonstrate/aggressive/data_imit_mem.pt')

In [13]:
a = ['james', 'charle']
print('{}'.format(a))

['james', 'charle']


In [14]:
nn.Mo

AttributeError: 'list' object has no attribute 'shape'

## Triple

In [1]:
import torch
import sys 
sys.path.append('..')
import os
from torch.utils.data.dataloader import DataLoader
import numpy as np
import torch

In [2]:
data_normal = torch.load('data/demonstrate/data_imit.pt')
data_aggressive = torch.load('utils/data/memory/temp/aggressive/data_imit_invisible.pt')


In [3]:
len(data_aggressive)

109271

In [8]:
len(data_normal)

4

In [7]:
data_aggressive[0][0][0].shape

torch.Size([6])

In [17]:
len(data_aggressive[0][0])

13

In [22]:
data_aggressive[4]

(tensor([[ 7.6927,  1.0000,  0.0000,  0.3000,  0.2773,  0.9608,  2.1412,  2.0438,
           0.5350, -0.8449,  0.3000,  2.9601,  0.6000],
         [ 7.6927,  1.0000,  0.0000,  0.3000,  0.2773,  0.9608,  6.1282,  1.4914,
          -0.7795, -0.6265,  0.3000,  6.3071,  0.6000],
         [ 7.6927,  1.0000,  0.0000,  0.3000,  0.2773,  0.9608,  5.9993, -1.4690,
          -0.9125,  0.4091,  0.3000,  6.1765,  0.6000],
         [ 7.6927,  1.0000,  0.0000,  0.3000,  0.2773,  0.9608,  1.7744, -2.7891,
           0.6384,  0.7697,  0.3000,  3.3057,  0.6000],
         [ 7.6927,  1.0000,  0.0000,  0.3000,  0.2773,  0.9608,  3.4091,  2.6102,
           0.1004, -0.9949,  0.3000,  4.2936,  0.6000]]),
 tensor([-0.7071,  0.7071]),
 tensor([0.3308]))